version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres16
    environment:
      POSTGRES_USER: ia_api
      POSTGRES_PASSWORD: S3cret
      POSTGRES_DB: db_islamic_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: